
### Pobranie listy uprawnień do pracy w KSeF nadanych osobom fizycznym

POST http://localhost:8082/permissions/query/persons/grants?pageOffset=0&pageSize=5
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "authorIdentifier": {
    "type": "Nip",
    "value": "string"
  },
  "authorizedIdentifier": {
    "type": "Nip",
    "value": "string"
  },
  "targetIdentifier": {
    "type": "Nip",
    "value": "string"
  },
  "permissionTypes": [
    "CredentialsManage"
  ],
  "permissionState": "Active"
}

### Pobranie listy uprawnień administratora podmiotu podrzędnego

POST http://localhost:8082/permissions/query/subunits/grants?pageOffset=0&pageSize=10
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "subunitIdentifier": {
    "type": "InternalId",
    "value": "string"
  }
}

### Pobranie listy uprawnień do obsługi faktur nadanych podmiotom

GET http://localhost:8082/permissions/query/entities/roles?pageOffset=0&pageSize=10
Accept: application/json
Authorization: {{token}}

### Pobranie listy uprawnień o charakterze upoważnień nadanych podmiotom

POST http://localhost:8082/permissions/query/authorizations/grants?pageOffset=0&pageSize=10
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "authorizingIdentifier": {
    "type": "Nip",
    "value": "string"
  },
  "authorizedIdentifier": {
    "type": "Nip",
    "value": "string"
  },
  "queryType": "Granted",
  "permissionTypes": [
    "SelfInvoicing"
  ]
}


### Pobranie listy uprawnień nadanych podmiotom unijnym

POST http://localhost:8082/permissions/query/eu-entities/grants?pageOffset=0&pageSize=10
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "vatUeIdentifier": "string",
  "authorizedFingerprintIdentifier": "string",
  "permissionTypes": [
    "CredentialsManage"
  ]
}