//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.akmf.ksef.sdk.client.model.xml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for anonymous complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Challenge"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;length value="36"/&gt;
 *               &lt;pattern value="\d{8}-CR-[A-F0-9]{10}-[A-F0-9]{10}-[A-F0-9]{2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ContextIdentifier" type="{http://ksef.mf.gov.pl/auth/token/2.0}TContextIdentifier"/&gt;
 *         &lt;element name="SubjectIdentifierType" type="{http://ksef.mf.gov.pl/auth/token/2.0}SubjectIdentifierTypeEnum"/&gt;
 *         &lt;element name="AuthorizationPolicy" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AllowedIps"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Ip4Address" maxOccurs="10" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                                   &lt;pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Ip4Range" maxOccurs="10" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                                   &lt;pattern value="((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)-((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Ip4Mask" maxOccurs="10" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                                   &lt;pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "challenge",
    "contextIdentifier",
    "subjectIdentifierType",
    "authorizationPolicy"
})
@XmlRootElement(name = "AuthTokenRequest")
public class AuthTokenRequest {

    @XmlElement(name = "Challenge", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String challenge;
    @XmlElement(name = "ContextIdentifier", required = true)
    protected TContextIdentifier contextIdentifier;
    @XmlElement(name = "SubjectIdentifierType", required = true)
    @XmlSchemaType(name = "token")
    protected SubjectIdentifierTypeEnum subjectIdentifierType;
    @XmlElement(name = "AuthorizationPolicy")
    protected AuthTokenRequest.AuthorizationPolicy authorizationPolicy;

    /**
     * Gets the value of the challenge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallenge() {
        return challenge;
    }

    /**
     * Sets the value of the challenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallenge(String value) {
        this.challenge = value;
    }

    /**
     * Gets the value of the contextIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link TContextIdentifier }
     *     
     */
    public TContextIdentifier getContextIdentifier() {
        return contextIdentifier;
    }

    /**
     * Sets the value of the contextIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContextIdentifier }
     *     
     */
    public void setContextIdentifier(TContextIdentifier value) {
        this.contextIdentifier = value;
    }

    /**
     * Gets the value of the subjectIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectIdentifierTypeEnum }
     *     
     */
    public SubjectIdentifierTypeEnum getSubjectIdentifierType() {
        return subjectIdentifierType;
    }

    /**
     * Sets the value of the subjectIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectIdentifierTypeEnum }
     *     
     */
    public void setSubjectIdentifierType(SubjectIdentifierTypeEnum value) {
        this.subjectIdentifierType = value;
    }

    /**
     * Gets the value of the authorizationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link AuthTokenRequest.AuthorizationPolicy }
     *     
     */
    public AuthTokenRequest.AuthorizationPolicy getAuthorizationPolicy() {
        return authorizationPolicy;
    }

    /**
     * Sets the value of the authorizationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthTokenRequest.AuthorizationPolicy }
     *     
     */
    public void setAuthorizationPolicy(AuthTokenRequest.AuthorizationPolicy value) {
        this.authorizationPolicy = value;
    }

    public AuthTokenRequest withChallenge(String value) {
        setChallenge(value);
        return this;
    }

    public AuthTokenRequest withContextIdentifier(TContextIdentifier value) {
        setContextIdentifier(value);
        return this;
    }

    public AuthTokenRequest withSubjectIdentifierType(SubjectIdentifierTypeEnum value) {
        setSubjectIdentifierType(value);
        return this;
    }

    public AuthTokenRequest withAuthorizationPolicy(AuthTokenRequest.AuthorizationPolicy value) {
        setAuthorizationPolicy(value);
        return this;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type&lt;/p&gt;.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
     * 
     * &lt;pre&gt;{&#064;code
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AllowedIps"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Ip4Address" maxOccurs="10" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *                         &lt;pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Ip4Range" maxOccurs="10" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *                         &lt;pattern value="((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)-((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Ip4Mask" maxOccurs="10" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *                         &lt;pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * }&lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allowedIps"
    })
    public static class AuthorizationPolicy {

        @XmlElement(name = "AllowedIps", required = true)
        protected AuthTokenRequest.AuthorizationPolicy.AllowedIps allowedIps;

        /**
         * Gets the value of the allowedIps property.
         * 
         * @return
         *     possible object is
         *     {@link AuthTokenRequest.AuthorizationPolicy.AllowedIps }
         *     
         */
        public AuthTokenRequest.AuthorizationPolicy.AllowedIps getAllowedIps() {
            return allowedIps;
        }

        /**
         * Sets the value of the allowedIps property.
         * 
         * @param value
         *     allowed object is
         *     {@link AuthTokenRequest.AuthorizationPolicy.AllowedIps }
         *     
         */
        public void setAllowedIps(AuthTokenRequest.AuthorizationPolicy.AllowedIps value) {
            this.allowedIps = value;
        }

        public AuthTokenRequest.AuthorizationPolicy withAllowedIps(AuthTokenRequest.AuthorizationPolicy.AllowedIps value) {
            setAllowedIps(value);
            return this;
        }


        /**
         * &lt;p&gt;Java class for anonymous complex type&lt;/p&gt;.
         * 
         * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
         * 
         * &lt;pre&gt;{&#064;code
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Ip4Address" maxOccurs="10" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
         *               &lt;pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Ip4Range" maxOccurs="10" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
         *               &lt;pattern value="((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)-((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){3}(25[0-5]|(2[0-4]|1\d|[1-9]|)\d)"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Ip4Mask" maxOccurs="10" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
         *               &lt;pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * }&lt;/pre&gt;
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ip4Address",
            "ip4Range",
            "ip4Mask"
        })
        public static class AllowedIps {

            @XmlElement(name = "Ip4Address")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> ip4Address;
            @XmlElement(name = "Ip4Range")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> ip4Range;
            @XmlElement(name = "Ip4Mask")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> ip4Mask;

            /**
             * Gets the value of the ip4Address property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the ip4Address property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getIp4Address().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * </p>
             * 
             * 
             * @return
             *     The value of the ip4Address property.
             */
            public List<String> getIp4Address() {
                if (ip4Address == null) {
                    ip4Address = new ArrayList<>();
                }
                return this.ip4Address;
            }

            /**
             * Gets the value of the ip4Range property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the ip4Range property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getIp4Range().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * </p>
             * 
             * 
             * @return
             *     The value of the ip4Range property.
             */
            public List<String> getIp4Range() {
                if (ip4Range == null) {
                    ip4Range = new ArrayList<>();
                }
                return this.ip4Range;
            }

            /**
             * Gets the value of the ip4Mask property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the ip4Mask property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getIp4Mask().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * </p>
             * 
             * 
             * @return
             *     The value of the ip4Mask property.
             */
            public List<String> getIp4Mask() {
                if (ip4Mask == null) {
                    ip4Mask = new ArrayList<>();
                }
                return this.ip4Mask;
            }

            public AuthTokenRequest.AuthorizationPolicy.AllowedIps withIp4Address(String... values) {
                if (values!= null) {
                    for (String value: values) {
                        getIp4Address().add(value);
                    }
                }
                return this;
            }

            public AuthTokenRequest.AuthorizationPolicy.AllowedIps withIp4Address(Collection<String> values) {
                if (values!= null) {
                    getIp4Address().addAll(values);
                }
                return this;
            }

            public AuthTokenRequest.AuthorizationPolicy.AllowedIps withIp4Range(String... values) {
                if (values!= null) {
                    for (String value: values) {
                        getIp4Range().add(value);
                    }
                }
                return this;
            }

            public AuthTokenRequest.AuthorizationPolicy.AllowedIps withIp4Range(Collection<String> values) {
                if (values!= null) {
                    getIp4Range().addAll(values);
                }
                return this;
            }

            public AuthTokenRequest.AuthorizationPolicy.AllowedIps withIp4Mask(String... values) {
                if (values!= null) {
                    for (String value: values) {
                        getIp4Mask().add(value);
                    }
                }
                return this;
            }

            public AuthTokenRequest.AuthorizationPolicy.AllowedIps withIp4Mask(Collection<String> values) {
                if (values!= null) {
                    getIp4Mask().addAll(values);
                }
                return this;
            }

        }

    }

}
