//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.akmf.ksef.sdk.client.model.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for TContextIdentifier complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="TContextIdentifier"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Nip" type="{http://ksef.mf.gov.pl/auth/token/2.0}TNIP"/&gt;
 *         &lt;element name="InternalId" type="{http://ksef.mf.gov.pl/auth/token/2.0}TIID"/&gt;
 *         &lt;element name="NipVatUe" type="{http://ksef.mf.gov.pl/auth/token/2.0}TNipVatUE"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TContextIdentifier", propOrder = {
    "nip",
    "internalId",
    "nipVatUe"
})
public class TContextIdentifier {

    /**
     * Numer Identyfikacyjny NIP
     * 
     */
    @XmlElement(name = "Nip")
    protected String nip;
    /**
     * Identyfikator wewnętrzny
     * 
     */
    @XmlElement(name = "InternalId")
    protected String internalId;
    /**
     * Kontekst złożony, będący połaczniem numeru NIP oraz numeru Vat UE
     * 
     */
    @XmlElement(name = "NipVatUe")
    protected String nipVatUe;

    /**
     * Numer Identyfikacyjny NIP
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNip() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNip()
     */
    public void setNip(String value) {
        this.nip = value;
    }

    /**
     * Identyfikator wewnętrzny
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalId() {
        return internalId;
    }

    /**
     * Sets the value of the internalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getInternalId()
     */
    public void setInternalId(String value) {
        this.internalId = value;
    }

    /**
     * Kontekst złożony, będący połaczniem numeru NIP oraz numeru Vat UE
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNipVatUe() {
        return nipVatUe;
    }

    /**
     * Sets the value of the nipVatUe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNipVatUe()
     */
    public void setNipVatUe(String value) {
        this.nipVatUe = value;
    }

    public TContextIdentifier withNip(String value) {
        setNip(value);
        return this;
    }

    public TContextIdentifier withInternalId(String value) {
        setInternalId(value);
        return this;
    }

    public TContextIdentifier withNipVatUe(String value) {
        setNipVatUe(value);
        return this;
    }

}
